# Generated by Django 4.2.11 on 2024-05-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bus_name',
            field=models.CharField(max_length=30, verbose_name='Автобус - име'),
        ),
        migrations.AlterField(
            model_name='book',
            name='busid',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Автобус id'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='book',
            name='dest',
            field=models.CharField(max_length=30, verbose_name='Крайна спирка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='book',
            name='nos',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Брой места'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='book',
            name='source',
            field=models.CharField(max_length=30, verbose_name='Начална спирка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('B', 'Запазено'), ('C', 'Отказано')], default='B', max_length=2, verbose_name='Състояние'),
        ),
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.TimeField(verbose_name='Час на тръгване'),
        ),
        migrations.AlterField(
            model_name='book',
            name='userid',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Клиент id'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_name',
            field=models.CharField(max_length=30, verbose_name='Име на линията'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='dest',
            field=models.CharField(max_length=30, verbose_name='Крайна спирка'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='nos',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Брой места в автобуса'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='rem',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Брой свободни места'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='source',
            field=models.CharField(max_length=30, verbose_name='Начална спирка'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='time',
            field=models.TimeField(verbose_name='Час на тръгване'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30, verbose_name='Парола'),
        ),
    ]
